spring:
  datasource:
    url: jdbc:postgresql://db:5432/pokemon
    username: admin
    password: admin
    driverClassName: org.postgresql.Driver
  
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: none

server:
  servlet:
    context-path: /api

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

mybatis:
  configuration:
    map-underscore-to-camel-case: true


